name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.0.1+3
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.18.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.7
  emoji_picker_flutter: ^1.3.0
  http: ^0.13.5
  html: ^0.15.1
  any_link_preview: ^2.0.9
  progress_indicators: ^1.0.0
  image_picker: ^0.8.6
  chat_composer: ^1.0.3
  just_audio: ^0.9.31
  rxdart: ^0.27.7
  flutter_keyboard_visibility: ^5.4.0
  file_picker: ^5.2.4
  video_compress: ^3.1.2
  video_player: ^2.4.10
  font_awesome_flutter: ^10.3.0
  audio_waveforms: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:


  assets:
    - assets/